import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { useEffect } from "react";
import { Col, Container, Row } from "react-bootstrap";
import ServicesCard from "../../Components/ServicesCard";

export default function Products() {
  const router = useRouter();
  const { id } = router.query;
  const [products, setProducts] = useState([]);
  const [category, setCategory] = useState([]);
  useEffect(() => {
    axios
      .get(
        `https://eurofins-backend.herokuapp.com/category`
      )
      .then((res) => {
        if (res.status === 200 || res.status === 201) {
          let categoryData = res.data.message;
          setCategory(categoryData);
        }
      })
      .catch((err) => console.log(err));
  });

  const filterCategory = category?.find(
    (x) => id === x.name
  );
  const updatedId = filterCategory?._id;
  useEffect(() => {
    if (
      updatedId &&
      updatedId !== "" &&
      updatedId !== "[id]"
    ) {
      axios
        .get(
          `https://eurofins-backend.herokuapp.com/product`
        )
        .then((res) => {
          const updatedRes = res.data.message;
          const filterProducts = updatedRes.filter(
            (x) => updatedId === x.category
          );

          setProducts(filterProducts);
        })
        .catch((err) => console.log(err));
    }
  }, [updatedId]);

  return (
    <div>
      <Head>
        <title>Products</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          {products?.map((x) => (
            <ServicesCard key={x._id} {...x} />
          ))}
        </Row>
      </Container>
    </div>
  );
}
