import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { useEffect } from "react";
import { Col, Container, Row } from "react-bootstrap";
import ServicesCard from "../../Components/ServicesCard";
import ConfidentialServices from "../../Sections/ConfidentialServices/ConfidentialServices";
import ProductGrid from "../../Sections/ProductGrid";

export default function Products() {
  const [products, setProducts] = useState([]);
  const router = useRouter();
  const path = router.asPath.split("/");
  const id = path[2];
  console.log("Category id", id);

  useEffect(() => {
    if (id && id !== "" && id !== "[id]") {
      axios
        .get(`http://localhost:4000/product`)
        .then((res) => {
          const updatedRes = res.data.message;
          const filterProducts = updatedRes.filter(
            (x) => id === x.category
          );
          setProducts(filterProducts);
        })
        .catch((err) => console.log(err));
    }
  }, [id]);

  return (
    <div>
      <Head>
        <title>Products</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ConfidentialServices filteredProducts={products} /> */}
      <Container>
        <Row>
          {products?.map((x) => (
            <ServicesCard key={x._id} {...x} />
          ))}
        </Row>
      </Container>
    </div>
  );
}
