import Head from "next/head";
import TestDetails from "../Sections/TestDetails/TestDetails";
import { getProductDetail } from "../redux/product-details/action";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { getProducts } from "../redux/product/action";

export default function TestDetailsPage() {
  const router = useRouter();
  const { id } = router.query;
  const dispatch = useDispatch();

  //! ---
  const products = useSelector(
    (state) => state.products?.products?.data?.message
  );

  useEffect(() => {
    dispatch(getProducts());
  }, []);
  //! ---

  const filterProductId = products?.find(
    (x) => id === x.name
  );
  const updatedId = filterProductId?._id;
  const productDetail = useSelector(
    (state) =>
      state.productDetail?.productDetail?.data?.message
  );

  useEffect(() => {
    if (updatedId) {
      dispatch(getProductDetail(updatedId));
    }
  }, [updatedId]);
  console.log("Product Details", productDetail);

  return (
    <div>
      <Head>
        <title>Eurofins Lab</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestDetails productDetail={productDetail} />
    </div>
  );
}
