import Head from "next/head";
import TestDetails from "../Sections/TestDetails/TestDetails";
import { getProductDetail } from "../redux/product-details/action";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";

export default function TestDetailsPage() {
  const router = useRouter();
  const { id } = router.query;
  const dispatch = useDispatch();

  const productDetail = useSelector(
    (state) => state.productDetail?.productDetail?.data?.message
  );

  useEffect(() => {
    if (id) { 
      dispatch(getProductDetail(id));
    }
  }, [id]);

  return (
    <div>
      <Head>
        <title>Eurofins Lab</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestDetails productDetail={productDetail} />
    </div>
  );
}
